title: Pranav Krishnan # name of the site
author: Pranav Krishnan # name of site's author
email: pranav@pkrshnan.com # email of site's author
url: https://pkrshnan.com # root address of the site
description: > # description of the site (multiple lines allowed)
  Just your average software developer.

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: pkrshnan/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

pagination:
  enabled: true
  permalink: '/page/:num/'
  per_page: 10
  sort_reverse: true
  trail:
    before: 1
    after: 1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate-v2
